name: CI

on:
  push:
    branches: [ base ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    uses: evolution-gaming/scala-github-actions/.github/workflows/ci.yml@999c04ccae0d79a8a0c12ed7d71136762b2ae8c1 # v7.1.0
    with:
      scala_versions: '["3.3.8"]'
