name: CI

on:
  push:
    branches: [ base ]
  pull_request:

jobs:
  test:
    uses: evolution-gaming/scala-github-actions/.github/workflows/ci.yml@v6
    secrets: inherit
    with:
      scala_versions: '["3.3.8"]'
