name: CI

on:
  push:
    branches: [ base ]
  pull_request:

jobs:
  test:
    uses: evolution-gaming/scala-github-actions/.github/workflows/ci.yml@dde27b9bd793d41d5aacf8fb74403c9de5da1146 # v6.3.0
    with:
      scala_versions: '["3.3.8"]'
